### PR TITLE
fix: only call WebFont.load if there are web fonts to load

### LINKED ISSUE #159: 🐞 [Bug Report] - JavaScript errors in Chrome console
**To Reproduce**
* Show JavaScript Console (View > Developer > JavaScript console)
* Launch webapp and navigate around
* Observe errors such as:  "webfont.js:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')"

**Expected behavior**
No errors in JavaScript console

### PR DESCRIPTION
**Pull request by glasnt**
## Description

Fixes #159 

**Note:** Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] Added steps to reproduce the changes in this pull request
- [ ] Added relevant testing in this pull request
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by glasnt** [comment]
Verifying fix through deployment (deploy-preview: avocano-preview-basic)

**Comment by glasnt** [comment]
Current deployment on https://avocano-preview-basic.web.app/ shows no error with this fix.

**Review by grayside — APPROVED** [review]
Nice tidy improvement. Might use the `perf:` prefix  from https://www.conventionalcommits.org if you want to flag performance improvements separately from bugs in general.

**Review by iennae — APPROVED** [review]

**Comment by glasnt** [comment]
@grayside this one isn't performance related, but I'll keep that in mind for the future!

**Pull request merged**
