### PR TITLE
Implement Deploystack

### PR DESCRIPTION
**Pull request by glasnt**
## Description

**Fixes:** #<ISSUE-NUMBER>

**Note:** Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] Added steps to reproduce the changes in this pull request
- [ ] Added relevant testing in this pull request
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by pattishin — APPROVED** [review]

**Comment by glasnt** [comment]
@tpryan PTAL

**Comment by tpryan** [comment]
Took a look. STELLAR. One note about adding an uptime check to the test to test that the run services actually work.

**Comment by glasnt** [comment]
Taking the terraform improvements from this PR into it's own, keeping this just to deploystack

**Comment by glasnt** [comment]
No longer in scope.

**Pull request closed without merging**
