### PR TITLE
feat: add OpenTelemetry tracing support

### PR DESCRIPTION
**Pull request by muncus**
- feat(o11y): Add tracing support for api server
- remove post_fork, and pin to one worker

## Description

uses opentelemetry's auto-instrumentation to export trace spans to Cloud Trace.

Fixes #<ISSUE-NUMBER>

**Note:** Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] Added steps to reproduce the changes in this pull request
- [ ] Added relevant testing in this pull request
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by glasnt** [comment]
Build warning:

```
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
```

Deploy error: startup check failed. (after enabling DEBUG on the deployment to see)

```
Bad Request: /ready
Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
```

Adding this value to ALLOWED_HOSTS, the service fails to deploy, with no useful logs (only linking back to the logs describing this error). 

```
Ready condition status changed to False for Revision server-00004-toy with message: The user-provided container failed the configured startup probe checks. Logs for this revision might contain more information.

For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
```

**Comment by glasnt** [comment]
confirmed this doesn't affect local dev in cloudshell

**Comment by glasnt** [comment]
also confirmed with @muncus that traces are coming through. Merging!

**Comment by muncus** [comment]
Example trace below showing a 3-tiered trace. The first 2 are from the Cloud Run Platform (load balancer, and appserver). The third span is from the app itself, with relevant labels from span context.

image

**Pull request merged**
